### PR TITLE
Tendenci 8

### PR DESCRIPTION
**Pull request by PaulSD**
This PR adds Python 3 support, upgrades to Django 1.11, and fixes lots of unrelated issues.

@aprildh31 and I are also working on upgrading to Bootstrap 4, but that work isn't as far along as the rest of this and still has some major issues, so I've decided to move that to a separate branch for the moment to avoid intermixing too many breaking changes at the same time.

I haven't thoroughly tested everything, so there are probably still some bugs to be found.  However, I have fixed all of the issues I am currently aware of, so this should be good enough for others to start testing.  This code should still be compatible with Python 2, however I have been primarily testing with Python 3, so it is possible I've missed some backward compatibility issues.

For anyone who wants to test, make sure you also use the updated project template: https://github.com/tendenci/tendenci-project-template/tree/tendenci8

Everything currently in the "python3_compatible" branch (and a lot more) is included here, so that branch is now obsolete.

This fixes various issues: #439 #595 #613 #650 #653

### CODE REVIEW

**Comment by jennyq** [comment]
Hi @PaulSD, 
Wow, what a PR! I haven't reviewed all commits yet. But I did run your branch on my local. It appears there is a TypeError "method-wrapper object is not an iterator" on content (pages, articles, ...) add/edit. The location of the error is at https://github.com/PaulSD/tendenci/blob/master/tendenci/apps/perms/fields.py#L145. Can you please take a look?

A new branch "tendenci8" has been created. The "entities" branch has been merged to master and will be deleted.  Since this PR also fixes many Python3 compatibility issues and Django 1.9/1.10/1.11 compatibility issues as you pointed out, I think it's better to merge it to the "tendenci8" branch. What do you think?

**Comment by PaulSD** [comment]
Ok, I'll look into that.

There are a few commits here that should definitely go into both Tendenci 7 and Tendenci 8, but most of them can go into Tendenci 8 only if you want.  I'll create a separate PR for the Tendenci 7 commits.

**Comment by PaulSD** [comment]
I've fixed the "method-wrapper object is not an iterator" issue and a bunch of other issues...

**Comment by PaulSD** [comment]
Adding a comment, since I know GitHub doesn't send notifications on PR changes...

I've made a whole lot of updates to this PR, so anyone who is following along might want to take another look at it.

**Comment by jennyq** [comment]
Very much appreciated for getting the ball rolling!
Although I haven't got the chance to finish reviewing all commits yet, let's move forward with the tendenci8 branch!

**Pull request merged**
