### PR TITLE
Adjust certificates to work in Chrome, Edge and Firefox

### PR DESCRIPTION
**Pull request by ssimmons42**

### CODE REVIEW

**Review by ndavis2 — DISMISSED** [review]

**Comment by jennyq** [comment]
Hi @ssimmons42,

For the single certificate, the format looks fine in FireFox, but still a bit out in Chrome (see the image below).

image

**Comment by ssimmons42** [comment]
Interesting it is still looking like this on your machine. Definitely had it working on Chrome before... I wonder if it has something to do with differences in the certificate images used. The CSS is set so that image height should be 1in... but it is possible if the test images you are using are larger than the ones I used maybe it takes up slightly more room and is causing this issue?  Could you check the exact height that the images are being rendered? I would like to compare it to what I have. Ultimately, it looks like we will probably just need to move that section up slightly to accommodate Chrome... but i was curious as to what is causing the difference.

**Comment by jennyq** [comment]
@ssimmons42, It's **not** about the image, but the item underneath the image where it is rendered as 3 lines instead of 2 lines. 
image

Btw, that's on the live site not on my machine.

**Comment by ssimmons42** [comment]
> @ssimmons42, It's **not** about the image, but the item underneath the image where it is rendered as 3 lines instead of 2 lines. image
> 
> Btw, that's on the live site not on my machine.

Oh ok, that makes sense. I just wanted to make sure nothing weird was happening with the CSS.

**Comment by ssimmons42** [comment]
@jennyq  Made another adjustment to the margins:

image

**Comment by jennyq** [comment]
> @jennyq Made another adjustment to the margins:
> 
> image

Thanks! I'll do some tests on the live site.

**Pull request merged**
