### PR TITLE
Add OpenOffice file formats, remove ppt

### LINKED ISSUE #854: Add support for LibreOffice/OpenOffice Document upload
Tendenci limits file uploads to a number of files, mostly Microsoft application documents, PDF and some image files.

Currently Tendenci doesn't support the upload of documents produced by OpenOffice/LibreOffice applications.  As these are open source office products used in preference to their Microsoft equivalents by many organisations, Tendenci should provide support for these.

Relevant document extensions/mimetypes are detailed in the [Wikipedia Open Document page](https://en.wikipedia.org/wiki/OpenDocument_technical_specification)

### PR DESCRIPTION
**Pull request by evanspaeder**
fix #854
Added OpenOffice / LibreOffice file types - document, spreadsheet, presentation. 

Also removed .ppt.  If we are not allowing .doc and .xls because of potential vulnerabilities / software EOL then it makes sense to also drop support for .ppt.

### CODE REVIEW

**Comment by jennyq** [comment]
Thanks @evanspaeder !

**Comment by jennyq** [comment]
@evanspaeder, Just checked the mime types list in the python mimetypes, those OpenOffice / LibreOffice file extensions are not in there. Which means those file types might still cannot be uploaded. Can you verify please?
https://github.com/python/cpython/blob/3.8/Lib/mimetypes.py#L413

**Comment by evanspaeder** [comment]
@jennyq Yes, you are right. I overlooked that.   

I think we will need to append a list of additional mime types to allowed_mime_types in the get_allowed_mimetypes() function.  I'll submit another PR in a bit.

**Comment by evanspaeder** [comment]
@jennyq  Can you take a look at this commit and let me know if you agree? 
https://github.com/Everblue-Tech/tendenci/commit/07780f7afceb86a54db22a7250e93580ac0df45a

**Comment by jennyq** [comment]
Maybe it's better to check and only add them if they're passed in file_exts, like this?

    od_types_map = {
        '.odt': 'application/vnd.oasis.opendocument.text',
        '.ods': 'application/vnd.oasis.opendocument.spreadsheet',
        '.odp': 'application/vnd.oasis.opendocument.presentation'
        }
    for ext in file_exts:
        if ext in types_map:
            mime_type = types_map[ext]
            if mime_type not in allowed_mimetypes:
                allowed_mimetypes.append(types_map[ext])
        elif ext in od_types_map:
            allowed_mimetypes.append(od_types_map[ext])

**Comment by evanspaeder** [comment]
@jennyq I think that looks good.

**Comment by jennyq** [comment]
Thanks @evanspaeder ! I've picked it up to the commit https://github.com/tendenci/tendenci/commit/5cf42c49553bfefb1efdac4386929c6127d22e70.

**Pull request merged**
