### PR TITLE
Add zoom

### PR DESCRIPTION
**Pull request by ssimmons42**

### CODE REVIEW

**Comment by shandy-bixly** [comment]
This is pending some testing with webinars. We need to schedule this with the client since it requires a Zoom account with webinars.

**Comment by jennyq** [comment]
Hi Shandy, 
Is this PR ready for review? Got this error when trying to run the `migrate` command.
ModuleNotFoundError: No module named 'jwt'

**Comment by shandy-bixly** [comment]
> Hi Shandy, Is this PR ready for review? Got this error when trying to run the `migrate` command. ModuleNotFoundError: No module named 'jwt'

@jennyq  I guess I must have already had jwt on my computer... since it worked I thought it was already installed. I will add it to the requirements file. However, there is a little bit of redesign that is going  to happen now based on something we found out while testing with the client. They will have multiple Zoom accounts that they will be using... I think we (you, me and Nicole) will have a meeting about it tomorrow morning. With the redesign, I would say it isn't fully ready now.

**Comment by jennyq** [comment]
> > Hi Shandy, Is this PR ready for review? Got this error when trying to run the `migrate` command. ModuleNotFoundError: No module named 'jwt'
> 
> @jennyq I guess I must have already had jwt on my computer... since it worked I thought it was already installed. I will add it to the requirements file. However, there is a little bit of redesign that is going to happen now based on something we found out while testing with the client this afternoon. They will have multiple Zoom accounts that they will be using... I think we (you, me and Nicole) will have a meeting about it tomorrow morning. With the redesign, I would say it isn't fully ready now.

Gotcha. Thanks. 

Regarding JWT, "Zoom is deprecating the JWT support as of June 1, 2023". Are we affected? https://developers.zoom.us/docs/internal-apps/jwt-faq/

**Comment by shandy-bixly** [comment]
> https://developers.zoom.us/docs/internal-apps/jwt-faq/

@jennyq 
Verified this is specifically the JWT app as shown in the screenshot below:

image


They specifically mention this here:
Note:

The [Meeting SDK authorization](https://developers.zoom.us/docs/meeting-sdk/auth/#generate-the-sdk-jwt) and [Video SDK authorization](https://developers.zoom.us/docs/video-sdk/auth/#generate-the-video-sdk-jwt) methods use JWTs to generate the SDK Auth signature. This has no association with the JWT app type.



(https://developers.zoom.us/docs/internal-apps/jwt-app-migration/)

**Comment by jennyq** [comment]
> > https://developers.zoom.us/docs/internal-apps/jwt-faq/
> 
> @jennyq Verified this is specifically the JWT app as shown in the screenshot below:
> 
> image
> 
> They specifically mention this here: Note:
> 
> The [Meeting SDK authorization](https://developers.zoom.us/docs/meeting-sdk/auth/#generate-the-sdk-jwt) and [Video SDK authorization](https://developers.zoom.us/docs/video-sdk/auth/#generate-the-video-sdk-jwt) methods use JWTs to generate the SDK Auth signature. This has no association with the JWT app type.
> 
> (https://developers.zoom.us/docs/internal-apps/jwt-app-migration/)

Ok, great. Thanks for verifying it @shandy-bixly !

**Comment by shandy-bixly** [comment]
@jennyq I have the updates ready to support multiple Zoom accounts. I've tested with 3 accounts (mine, Nichole's, and the client's) but I will continue testing while waiting for the review to be complete. If I catch a bug & need to fix something during that time, I will let you know

**Comment by shandy-bixly** [comment]
@jennyq I found a bug but have a fix. The reason my API credentials didn't work is because my browser was auto filing the secret field because it was a PasswordInput field... I had to add `attrs={'autocomplete': 'new-password'})` so it would stop overwritting it every time I opened it

**Comment by shandy-bixly** [comment]
@jennyq  I pushed up the commit with the use_as_default field. There's also a fix in there so that is_zoom_webinar is hidden/shown correctly

**Comment by shandy-bixly** [comment]
@jennyq Can you give me the links for the documentation again? I seem to have lost them.

**Comment by shandy-bixly** [comment]
> @jennyq Can you give me the links for the documentation again? I seem to have lost them.

I have it now

**Pull request merged**
