### PR TITLE
Don't show soft-deleted objects

### PR DESCRIPTION
**Pull request by vladkorkach**
Solution for #555 
I've added a filter which doesn't show data marked as deleted.

### CODE REVIEW

**Comment by jennyq** [comment]
Thank you!

**Comment by FourthEstate** [comment]
vladkorkach  contact me for some work.

**Comment by FourthEstate** [comment]
Note that this introduces a new issue where additional corporate membership types can't be added if a "hidden" category has same name.  

Delete should really be a DELETE, not just a hide

screen shot 2017-03-12 at 3 49 17 pm

**Comment by jennyq** [comment]
@FourthEstate, the delete is set to soft-delete for a reason so that if someone accidentally deleted an item and wanted it back, it'd be easy to pull back. However there **IS** a way to physically delete the soft-deleted items - just run the command `delete_soft_deleted_items`. You can add this command to the cron jobs to run nightly if needed.

**Pull request merged**
