### PR TITLE
Add membership type to member cards

### PR DESCRIPTION
**Pull request by bernd-wechner**
Contributes to https://github.com/tendenci/tendenci/issues/937

### CODE REVIEW

**Comment by bernd-wechner** [comment]
Am still getting my head around PRs local branches. Feedback welcome, this looks like it has a lot of dross in the summary above, but the File Changed tab I'm happy with, after removing a hitchhiker.

**Comment by bernd-wechner** [comment]
This fixes part of https://github.com/tendenci/tendenci/issues/937

**Comment by jennyq** [comment]
Thanks!

Next time when you work on a new PR, please make sure your local branch is synced with the upstream/master to prevent your commits from being mixed with those non-relevant commits.
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by bernd-wechner** [comment]
Thanks Jenny. Am learning a PR workflow rapidly, so nosediving into local, origin and upstream repos. But yes, I try to keep master origin synced with master upstream and apply changes to a branch on master origin. I keep local and origin development branches with all PRs merged and the workflow is stabilising but a lot to learn about branching, merging, stashing, cherry picking to manage a half dozen small differential PRs at once (which is the novelty for me).

**Pull request merged**
