### PR TITLE
Minor update docs

### PR DESCRIPTION
**Pull request by goetzk**
Hi guys,
Not sure if this is a useful thing to have but here are some minor update commands i've picked up as i've experimented with tendenci. If something like this is desirable i'll fix the tiem typo (oops) and remove the footer before re requesting a pull.

### CODE REVIEW

**Comment by eschipul** [comment]
Excellent addition!

**Comment by jennyq** [comment]
Nice one! But without specify the version, the `pip install tendenci --upgrade`  can be dangerous. It was fine when we only had T5. Not sure what would be a better alternative. Maybe with the new file requirements/tendenci.txt introduced in T7, a minor update can run `pip install -r requirements/tendenci.txt --upgrade`.

This is what we have in `requirements/tendenci.txt` right now:

    https://github.com/tendenci/tendenci/archive/master.zip
    # tendenci>=7,<8  # replace the above link with this later 

    https://github.com/epantry/django-sql-explorer/archive/master.zip 

Once the `django-sql-explorer` issues a new release to PyPi, we can pull it into tendenci core. The only thing left at that time would be ` tendenci>=7,<8`...

**Comment by eschipul** [comment]
@goetzk I think @jennyq has a valid point. Additionally I didn't realize this was merging into 7.1. Right now all merges need to go straight to "master" (after being tested of course) so we can get it out to pypi. (We'll get back to a nightly build soon. But for now, it's all or nothing.) 

For this commit, would you mind removing the pip install portion and resubmitting the pull request direct to master so we don't have to merge and it so it shows up on readthedocs? And it will show you as the author - as it should. Not trying to make more work for you, I just want to be sure people see your contributions with your name on them.

Topic 2 - You also submitted another much larger pull submit to 7.1 which has 12 changes. Any chance you can resubmit those individually to master as I'm not sure 100% of the 12 changes are aligned and honestly I'm not sure how to do a partial pull commit. Yet I also fully understand the importance of attribution so I feel strongly that your name should be on the commits. And the number of commits isn't something I think any of us worry about as much as the quality. You've got some great stuff in there that I'd love to get into master!

**Comment by goetzk** [comment]
I have re pushed the branch. I can open a new pull request or you can cherry pick the two commits out of my new push - whichever you would prefer.

**Comment by jennyq** [comment]
@goetzk, yes please open a new pull request and make your branch based on master instead of tendenci7. The master branch is on 7.1. You can use the tendenci-project-template 7.1 https://github.com/tendenci/tendenci-project-template/tree/tendenci7.1 to set up a site on your local. Let us know if you have any question. Thanks!

**Comment by eschipul** [comment]
@jennyq wouldn't it be easier for a documentation update to do a pull against master? I do get needing to test code changes but if the docs aren't in master they won't replicate to readthedocs if I understand it correctly? Honest question - I'm probably wrong and just trying to understand.

**Comment by jennyq** [comment]
@eschipul yes, need to be in master for docs to show on readthedocs. That's what I was asking. 

I thought @goetzk might need to set up a T7.1 site so I mentioned the **tendenci-project-template**. The current master branch of **tendenci-project-template** https://github.com/tendenci/tendenci-project-template is for T7.0, **not** T7.1 sites. Should we switch tendenci7.1 to master branch now  or wait until we push 7.1 to pypi?

**Pull request merged**
